CREATE TABLE player_match_reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player_id BIGINT NOT NULL,
    biwenger_match_id BIGINT NOT NULL,
    biwenger_round_id BIGINT,
    round_name VARCHAR(100),
    round_short VARCHAR(20),
    match_date TIMESTAMP WITHOUT TIME ZONE,
    season VARCHAR(20),
    participated BOOLEAN NOT NULL,
    absence_status VARCHAR(50),
    points INTEGER,

    CONSTRAINT uk_player_match_report_player_match
        UNIQUE (player_id, biwenger_match_id),

    CONSTRAINT fk_player_match_report_player
        FOREIGN KEY (player_id)
        REFERENCES players(id)
);