spring.application.name=biwenger-assistant

spring.datasource.url=jdbc:postgresql://localhost:5432/biwenger
spring.datasource.username=biwenger
spring.datasource.password=biwenger

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false