spring.application.name=biwenger-assistant

spring.datasource.url=jdbc:postgresql://localhost:5432/biwenger
spring.datasource.username=biwenger
spring.datasource.password=biwenger

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

biwenger.base-url=${BIWENGER_BASE_URL:https://biwenger.as.com}
biwenger.token=${BIWENGER_TOKEN}
biwenger.league-id=${BIWENGER_LEAGUE_ID}
biwenger.user-id=${BIWENGER_USER_ID}
biwenger.version=${BIWENGER_VERSION}
biwenger.language=${BIWENGER_LANGUAGE:es}
biwenger.cdn-base-url=${BIWENGER_CDN_BASE_URL:https://cf.biwenger.com}
biwenger.competition=${BIWENGER_COMPETITION:la-liga}
biwenger.score=${BIWENGER_SCORE:100}